# -*- coding: utf-8 -*-
"""Syntax_Surgeon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12f95UiWDCbxUg8LH7F2ke3pSnFM_pmWa
"""

!pip install autopep8
!pip install gradio

import autopep8
import gradio as gr

def fix_code(code):
    try:
        fixed_code = autopep8.fix_code(code)
        return fixed_code
    except Exception as e:
        return str(e)

interface = gr.Interface(
    fn=fix_code,
    inputs=gr.Textbox(lines=15, label="Enter your Python Code"),
    outputs=gr.Textbox(lines=15, label="Fixed Code"),
    title="Syntax Surgeon - AI Code Fixer",
    description="This tool detects and fixes Python syntax errors automatically."
)

interface.launch()